# config.yaml

size: 800
inf_name: "fasterrcnn_lora-True_bs-4_lr-0.00036395119764864127_accum-1_size-800-val_map=0.90.ckpt"

model:
  nclasses: 2
  model_type: "fasterrcnn" # swin, fasterrcnn, custom
  backbone_name: "swin_base_patch4_window7_224"
  fpn: false
  size: ${size}
  lora: true

paths:
  test: "data/test/"
  labels: "data/labels.json"
  output_images: "output/"
  model_path: "models/fasterrcnn"

test_transforms:
  - name: Resize
    height: ${size}
    width: ${size}
    p: 1.0

  - name: Normalize
    mean: [0, 0, 0]
    std: [1, 1, 1]
    max_pixel_value: 255.0

  - name: ToTensorV2
